parameters:
    ccdn_component_bb_code.extension.class:                        CCDNComponent\BBCodeBundle\Extension\BBCodeExtension
#    bb_code_fetch_choices.extension.class:          CCDNComponent\BBCodeBundle\Extension\BBCodeFetchChoicesExtension
    ccdn_component_bb_code.bb_code.engine.class:    CCDNComponent\BBCodeBundle\Engine\BBCodeEngine

services:
    bb_code.extension:
        class: %ccdn_component_bb_code.extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
#    bb_code_fetch_choices.extension:
#        class: %bb_code_fetch_choices.extension.class%
#        arguments: [@service_container]
#        tags:
#            - { name: twig.extension }
    bb_code.engine:
        class:  %ccdn_component_bb_code.bb_code.engine.class%
        arguments: [@service_container]