parameters:
    bb_code.extension.class:                        CodeConsortium\BBCodeBundle\Extension\BBCodeExtension
#    bb_code_fetch_choices.extension.class:          CodeConsortium\BBCodeBundle\Extension\BBCodeFetchChoicesExtension
    code_consortium_bbcode.bb_code.engine.class:    CodeConsortium\BBCodeBundle\Engine\BBCodeEngine

services:
    bb_code.extension:
        class: %bb_code.extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
#    bb_code_fetch_choices.extension:
#        class: %bb_code_fetch_choices.extension.class%
#        arguments: [@service_container]
#        tags:
#            - { name: twig.extension }
    bb_code.engine:
        class:  %code_consortium_bbcode.bb_code.engine.class%
        arguments: [@service_container]